name: puzzle_game
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.7.0
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  page_transition: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  audioplayers: ^4.1.0
  shared_preferences: ^2.1.2
  get_it: ^7.6.0
  dio: ^5.2.0+1
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.1
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  build_runner: ^2.3.3
  equatable: ^2.0.5
  flutter_styled_toast: ^2.1.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/puzzle_photos/4.jpg
    - assets/images/puzzle_photos/3.jpg
    - assets/images/puzzle_photos/0.jpg
    - assets/images/puzzle_photos/6.jpg
    - assets/images/puzzle_photos/7.jpg
    - assets/images/puzzle_photos/8.jpg
    - assets/images/puzzle_photos/9.jpg
    - assets/images/puzzle_photos/0.jpg
    - assets/images/puzzle_photos/1.jpg
    - assets/images/puzzle_photos/2.jpg
    - assets/images/puzzle_photos/5.jpg
    - assets/images/puzzle_photos/10.jpg
    - assets/images/puzzle_photos/11.jpg
    - assets/images/puzzle_photos/12.jpg
    - assets/images/puzzle_photos/13.jpg
    - assets/images/puzzle_photos/14.jpg
    - assets/images/puzzle_photos/15.jpg
    - assets/images/puzzle_photos/16.jpg
    - assets/images/puzzle_photos/17.jpg
    - assets/images/puzzle_photos/18.jpg
    - assets/images/puzzle_photos/19.jpg
    - assets/images/puzzle_photos/20.jpg
    - assets/images/puzzle_photos/21.jpg
    - assets/images/puzzle_photos/22.jpg
    - assets/images/puzzle_photos/23.jpg
    - assets/images/puzzle_photos/24.jpg
    - assets/images/puzzle_photos/25.jpg
    - assets/images/puzzle_photos/26.jpg
    - assets/images/puzzle_photos/27.jpg


    - assets/images/background-2.jpg
    - assets/images/golden_coin.png
    - assets/images/log_in.png
    - assets/images/logo.png
    - assets/audios/finish_game.mp3

    - assets/audios/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
